spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: root
  quartz:
    job-store-type: jdbc
# org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate

logging.level: info
